# Generated by Django 4.2.25 on 2025-10-30 00:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique patient identifier (UUID)', primary_key=True, serialize=False)),
                ('mrn', models.CharField(blank=True, help_text='Local medical record number (optional)', max_length=50, null=True, unique=True, verbose_name='Medical Record Number')),
                ('first_name', models.CharField(help_text="Patient's first/given name", max_length=100)),
                ('last_name', models.CharField(help_text="Patient's last/family name", max_length=100)),
                ('middle_names', models.CharField(blank=True, help_text='Middle name(s) if any', max_length=100, null=True)),
                ('dob', models.DateField(blank=True, help_text="Patient's date of birth", null=True, verbose_name='Date of Birth')),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('U', 'Unknown')], help_text="Patient's sex", max_length=20, null=True)),
                ('contact_json', models.JSONField(blank=True, default=dict, help_text='Contact details: phones, emails (JSON format)', null=True)),
                ('address_json', models.JSONField(blank=True, default=dict, help_text='Address details (JSON format)', null=True)),
                ('emergency_json', models.JSONField(blank=True, default=dict, help_text='Emergency contact details (JSON format)', null=True)),
                ('flags_json', models.JSONField(blank=True, default=dict, help_text='Risk flags, alerts, notes (JSON format)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when patient record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when patient record was last updated')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'db_table': 'patients',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='patients_last_na_ce6411_idx'), models.Index(fields=['mrn'], name='patients_mrn_5d1fc1_idx'), models.Index(fields=['created_at'], name='patients_created_b2d3e4_idx')],
            },
        ),
    ]
