# Generated by Django 4.2.25 on 2025-11-04 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
        ('clinicians', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='clinic',
            field=models.ForeignKey(blank=True, help_text='Clinic location for this patient', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='clinicians.clinic'),
        ),
        migrations.AddField(
            model_name='patient',
            name='coordinator_date',
            field=models.DateField(blank=True, help_text='Date when coordinator was assigned', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='coordinator_name',
            field=models.CharField(blank=True, help_text="Coordinator name (e.g., 'Warda - Ability Connect')", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='funding_type',
            field=models.ForeignKey(blank=True, help_text="Patient's funding source (NDIS, Private, DVA, etc.)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='settings.fundingsource'),
        ),
        migrations.AddField(
            model_name='patient',
            name='health_number',
            field=models.CharField(blank=True, help_text='Health number (different from MRN)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='notes',
            field=models.TextField(blank=True, help_text='General notes about the patient', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='plan_end_date',
            field=models.DateField(blank=True, help_text='NDIS plan end date', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='plan_start_date',
            field=models.DateField(blank=True, help_text='NDIS plan start date', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr.'), ('Mrs', 'Mrs.'), ('Ms', 'Ms.'), ('Miss', 'Miss'), ('Dr', 'Dr.'), ('Prof', 'Prof.')], help_text="Patient's title (Mr., Mrs., Ms., Dr., etc.)", max_length=10, null=True),
        ),
    ]
