# Generated by Django 4.2.25 on 2025-11-04 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_clinic_patient_coordinator_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='archived',
            field=models.BooleanField(default=False, help_text='Whether this patient has been archived (soft deleted)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when patient was archived', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='archived_by',
            field=models.CharField(blank=True, help_text='User who archived this patient (optional)', max_length=100, null=True),
        ),
    ]
