# Generated by Django 4.2.25 on 2025-11-04 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_archived_patient_archived_at_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['archived'], name='patients_archive_5c56ec_idx'),
        ),
    ]
