# Generated by Django 4.2.25 on 2025-11-04 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_patients_archive_5c56ec_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='plan_dates_json',
            field=models.JSONField(blank=True, default=list, help_text='Array of plan dates: [{"start_date": "YYYY-MM-DD", "end_date": "YYYY-MM-DD", "type": "1 Year Plan"}, ...]', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='plan_end_date',
            field=models.DateField(blank=True, help_text='NDIS plan end date (legacy - use plan_dates_json for multiple dates)', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='plan_start_date',
            field=models.DateField(blank=True, help_text='NDIS plan start date (legacy - use plan_dates_json for multiple dates)', null=True),
        ),
    ]
