# Generated by Django 4.2.25 on 2025-11-14 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_patient_plan_dates_json_alter_patient_plan_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='filemaker_metadata',
            field=models.JSONField(blank=True, help_text='FileMaker import metadata (filemaker_id, filemaker_clinic, xero_contact_id, imported_at, etc.)', null=True),
        ),
    ]
