# Generated by Django 4.2.25 on 2025-11-14 01:17

from django.db import migrations
import json


def migrate_filemaker_metadata(apps, schema_editor):
    """
    Move FileMaker metadata from notes field to filemaker_metadata JSON field.
    
    Example notes content:
    {"filemaker_id": "2F98F705-C85E-4957-B006-CC5B62273B92", "filemaker_clinic": "Tamworth", 
     "xero_contact_id": "", "imported_at": "2025-11-09T10:46:22.444317"}
    """
    Patient = apps.get_model('patients', 'Patient')
    
    migrated_count = 0
    skipped_count = 0
    
    # Find all patients with notes
    for patient in Patient.objects.all():
        if not patient.notes:
            continue
            
        # Try to parse the notes as JSON
        try:
            # Check if notes looks like JSON
            if patient.notes.strip().startswith('{') and patient.notes.strip().endswith('}'):
                metadata = json.loads(patient.notes)
                
                # Check if it's FileMaker metadata (has filemaker_id key)
                if 'filemaker_id' in metadata:
                    # Move to filemaker_metadata field
                    patient.filemaker_metadata = metadata
                    
                    # Clear the notes (or keep it if you want)
                    patient.notes = ''
                    
                    patient.save(update_fields=['filemaker_metadata', 'notes'])
                    
                    migrated_count += 1
                    print(f"Migrated FileMaker metadata for patient {patient.id} ({patient.first_name} {patient.last_name})")
                else:
                    # It's valid JSON but not FileMaker metadata - leave it alone
                    skipped_count += 1
            else:
                # Notes are not JSON - leave them alone
                skipped_count += 1
        except json.JSONDecodeError:
            # Notes are not valid JSON - leave them alone
            skipped_count += 1
            continue
    
    print(f"\n✅ Migration complete: {migrated_count} patients migrated, {skipped_count} patients skipped (non-FileMaker notes)")


def reverse_migrate_filemaker_metadata(apps, schema_editor):
    """
    Reverse migration: move filemaker_metadata back to notes
    """
    Patient = apps.get_model('patients', 'Patient')
    
    for patient in Patient.objects.filter(filemaker_metadata__isnull=False):
        if patient.filemaker_metadata:
            patient.notes = json.dumps(patient.filemaker_metadata)
            patient.filemaker_metadata = None
            patient.save(update_fields=['filemaker_metadata', 'notes'])


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_add_filemaker_metadata'),
    ]

    operations = [
        migrations.RunPython(migrate_filemaker_metadata, reverse_migrate_filemaker_metadata),
    ]

