# Generated by Django 4.2.25 on 2025-11-15 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_add_filemaker_metadata 2'),
        ('patients', '0007_migrate_filemaker_data_from_notes'),
        ('patients', '0007_migrate_filemaker_data_from_notes 2'),
    ]

    operations = [
    ]
