# Generated by Django 4.2.25 on 2025-11-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_merge_20251116_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='ndis_plan_end_date',
            field=models.DateField(blank=True, help_text='NDIS plan end date (from FileMaker Contacts.xlsx)', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='ndis_plan_start_date',
            field=models.DateField(blank=True, help_text='NDIS plan start date (from FileMaker Contacts.xlsx)', null=True),
        ),
    ]
