# Generated by Django 4.2.25 on 2025-11-20 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_patient_ndis_plan_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='funding_source',
            field=models.CharField(blank=True, choices=[('NDIS', 'NDIS'), ('DVA', 'DVA'), ('ENABLE', 'Enable'), ('BUPA', 'BUPA'), ('MEDIBANK', 'Medibank'), ('AHM', 'AHM'), ('PRIVATE', 'Private/Self-Funded'), ('OTHER', 'Other')], help_text="Patient's primary funding source for billing/invoicing", max_length=50, null=True),
        ),
    ]
