# Generated by Django 4.2.25 on 2025-11-20 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_patient_funding_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='funding_source',
            field=models.CharField(blank=True, help_text="Patient's primary funding source for billing/invoicing (e.g., 'NDIS', 'ENABLE', 'BUPA')", max_length=50, null=True),
        ),
    ]
