# Generated by Django 4.2.25 on 2025-11-08 23:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text="Contact's first name", max_length=100)),
                ('last_name', models.CharField(help_text="Contact's last name", max_length=100)),
                ('contact_type', models.CharField(choices=[('CARER', 'Carer'), ('FAMILY', 'Family'), ('EMERGENCY_CONTACT', 'Emergency Contact'), ('SUPPLIER', 'Supplier'), ('OTHER', 'Other')], default='OTHER', help_text='Type of contact', max_length=50)),
                ('contact_json', models.JSONField(blank=True, default=dict, help_text='Contact details (phone, email, mobile)', null=True)),
                ('address_json', models.JSONField(blank=True, default=dict, help_text='Address details', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this contact', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'General Contact',
                'verbose_name_plural': 'General Contacts',
                'db_table': 'general_contacts',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='general_con_last_na_e1f579_idx'), models.Index(fields=['contact_type'], name='general_con_contact_ffc595_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContactRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_object_id', models.UUIDField(help_text='UUID of source contact')),
                ('to_object_id', models.UUIDField(help_text='UUID of target contact')),
                ('relationship_type', models.CharField(choices=[('CARER', 'Carer'), ('PARENT', 'Parent'), ('SPOUSE', 'Spouse'), ('CHILD', 'Child'), ('SIBLING', 'Sibling'), ('EMERGENCY_CONTACT', 'Emergency Contact'), ('ALSO_PATIENT', 'Also a Patient'), ('ALSO_REFERRER', 'Also a Referrer'), ('ALSO_COORDINATOR', 'Also a Coordinator')], help_text='Type of relationship', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Additional relationship notes', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this relationship currently active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_content_type', models.ForeignKey(help_text='Content type of source contact', on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='contenttypes.contenttype')),
                ('to_content_type', models.ForeignKey(help_text='Content type of target contact', on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Contact Relationship',
                'verbose_name_plural': 'Contact Relationships',
                'db_table': 'contact_relationships',
                'ordering': ['-is_active', '-created_at'],
                'indexes': [models.Index(fields=['from_content_type', 'from_object_id', 'is_active'], name='contact_rel_from_co_7cfcf9_idx'), models.Index(fields=['to_content_type', 'to_object_id', 'is_active'], name='contact_rel_to_cont_31e6e5_idx'), models.Index(fields=['relationship_type'], name='contact_rel_relatio_ec9f1e_idx')],
            },
        ),
    ]
