# Generated by Django 4.2.25 on 2025-11-09 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='filemaker_event_id',
            field=models.UUIDField(blank=True, help_text='Original FileMaker appointment ID (for import tracking)', null=True, unique=True),
        ),
    ]
