# Generated by Django 4.2.25 on 2025-11-10 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinicians', '0002_add_filemaker_id_to_clinic'),
        ('appointments', '0002_appointment_filemaker_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='clinic',
            field=models.ForeignKey(blank=True, help_text='Clinic location for this appointment (null for historical appointments with archived clinics)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='clinicians.clinic'),
        ),
    ]
