# Generated by Django 4.2.25 on 2025-11-10 07:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointment_clinic'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Name of appointment type (e.g., 'Initial Consultation')", max_length=100, unique=True)),
                ('default_duration_minutes', models.IntegerField(default=30, help_text='Default duration in minutes')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this type is active and available for use')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Appointment Type',
                'verbose_name_plural': 'Appointment Types',
                'db_table': 'appointment_types',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.ForeignKey(blank=True, help_text='Type of appointment (e.g., Initial Consultation, Follow-up)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='appointments.appointmenttype'),
        ),
    ]
