# Generated by Django 4.2.25 on 2025-11-15 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointment_clinic 2'),
        ('appointments', '0003_alter_appointment_clinic 3'),
        ('appointments', '0004_appointmenttype_appointment_appointment_type'),
        ('appointments', '0004_appointmenttype_appointment_appointment_type 2'),
        ('appointments', '0004_appointmenttype_appointment_appointment_type 3'),
    ]

    operations = [
    ]
