# Generated by Django 4.2.25 on 2025-11-16 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('appointments', '0005_merge_20251116_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='billing_company',
            field=models.ForeignKey(blank=True, help_text='Company involved in billing (shown in reference or as contact)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billed_appointments', to='companies.company'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='billing_notes',
            field=models.TextField(blank=True, help_text='PO number, special billing instructions, etc.'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='invoice_contact_type',
            field=models.CharField(choices=[('patient', 'Patient as Primary Contact'), ('company', 'Company as Primary Contact')], default='patient', help_text='Who should be the primary Xero contact on the invoice?', max_length=20),
        ),
    ]
