# Generated by Django 4.2.25 on 2025-11-21 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_add_xero_billing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='followup_scheduled',
            field=models.BooleanField(default=False, help_text='Flag to indicate a follow-up has been scheduled for this appointment'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='needs_followup_reminder',
            field=models.BooleanField(default=False, help_text='Flag to indicate this appointment needs a follow-up scheduled'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='parent_appointment',
            field=models.ForeignKey(blank=True, help_text='If this is a follow-up, link to the original appointment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup_appointments', to='appointments.appointment'),
        ),
    ]
