# Generated by Django 4.2.25 on 2025-11-21 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_remove_funding_source_choices'),
        ('appointments', '0007_add_followup_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(blank=True, help_text='Patient for this appointment (optional for all-day clinic events)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='patients.patient'),
        ),
    ]
