# Generated by Django 4.2.25 on 2025-11-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_make_patient_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_recurring',
            field=models.BooleanField(db_index=True, default=False, help_text='Is this appointment part of a recurring series?'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='recurrence_end_date',
            field=models.DateField(blank=True, help_text='Last date for recurring appointments (inclusive)', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='recurrence_group_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Links recurring appointments together (same ID for all in series)', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='recurrence_pattern',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Every 2 Weeks'), ('monthly', 'Monthly')], help_text='How often does this appointment repeat?', max_length=20, null=True),
        ),
    ]
