# Generated by Django 4.2.25 on 2025-11-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_add_recurring_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='sms_confirmation_message',
            field=models.TextField(blank=True, help_text="The actual SMS reply message from patient (e.g., 'YES', 'CONFIRM')", null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='sms_confirmed',
            field=models.BooleanField(db_index=True, default=False, help_text='Has patient confirmed appointment via SMS reply?'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='sms_confirmed_at',
            field=models.DateTimeField(blank=True, help_text='When did patient confirm via SMS?', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='sms_reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='When was the SMS reminder sent?', null=True),
        ),
    ]
