# Generated by Django 4.2.25 on 2025-11-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_add_sms_confirmation_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='sms_cancellation_message',
            field=models.TextField(blank=True, help_text="The actual SMS cancellation message from patient (e.g., 'CANT MAKE IT')", null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='sms_cancelled',
            field=models.BooleanField(db_index=True, default=False, help_text='Has patient cancelled appointment via SMS reply?'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='sms_cancelled_at',
            field=models.DateTimeField(blank=True, help_text='When did patient cancel via SMS?', null=True),
        ),
    ]
