# Generated by Django 4.2.25 on 2025-11-08 23:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('patients', '0005_patient_plan_dates_json_alter_patient_plan_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Medical specialty name', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Specialty',
                'verbose_name_plural': 'Specialties',
                'db_table': 'specialties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Referrer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, help_text='Title: Mr, Mrs, Dr, Prof, etc.', max_length=10, null=True)),
                ('first_name', models.CharField(help_text="Referrer's first name", max_length=100)),
                ('last_name', models.CharField(help_text="Referrer's last name", max_length=100)),
                ('contact_json', models.JSONField(blank=True, default=dict, help_text='Contact details (phone, email, mobile) - same structure as patients', null=True)),
                ('address_json', models.JSONField(blank=True, default=dict, help_text='Address details', null=True)),
                ('practice_name', models.CharField(blank=True, help_text='Name of medical practice', max_length=200, null=True)),
                ('filemaker_id', models.UUIDField(blank=True, help_text='Original FileMaker referrer ID (for import tracking)', null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, help_text='Links to medical practice/company', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrers', to='companies.company')),
                ('specialty', models.ForeignKey(blank=True, help_text='Medical specialty', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrers', to='referrers.specialty')),
            ],
            options={
                'verbose_name': 'Referrer',
                'verbose_name_plural': 'Referrers',
                'db_table': 'referrers',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='PatientReferrer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referral_date', models.DateField(blank=True, help_text='Date of referral', null=True)),
                ('referral_reason', models.TextField(blank=True, help_text='Reason for referral', null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PENDING', 'Pending')], default='ACTIVE', help_text='Referral status', max_length=20)),
                ('filemaker_id', models.UUIDField(blank=True, help_text='Original FileMaker join record ID', null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(help_text='Patient being referred', on_delete=django.db.models.deletion.CASCADE, related_name='patient_referrers', to='patients.patient')),
                ('referrer', models.ForeignKey(help_text='Referrer who referred the patient', on_delete=django.db.models.deletion.CASCADE, related_name='patient_referrers', to='referrers.referrer')),
            ],
            options={
                'verbose_name': 'Patient Referrer',
                'verbose_name_plural': 'Patient Referrers',
                'db_table': 'patient_referrers',
                'ordering': ['-referral_date'],
            },
        ),
        migrations.CreateModel(
            name='ReferrerCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.CharField(blank=True, help_text='Position at practice (e.g., Senior Podiatrist, GP Partner)', max_length=100, null=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Is this their primary practice?')),
                ('filemaker_id', models.UUIDField(blank=True, help_text='Original FileMaker join record ID', null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='Company/Medical Practice', on_delete=django.db.models.deletion.CASCADE, related_name='referrer_companies', to='companies.company')),
                ('referrer', models.ForeignKey(help_text='Referrer', on_delete=django.db.models.deletion.CASCADE, related_name='referrer_companies', to='referrers.referrer')),
            ],
            options={
                'verbose_name': 'Referrer Company',
                'verbose_name_plural': 'Referrer Companies',
                'db_table': 'referrer_companies',
                'ordering': ['-is_primary', 'company__name'],
                'indexes': [models.Index(fields=['referrer', 'is_primary'], name='referrer_co_referre_e45ea7_idx'), models.Index(fields=['company'], name='referrer_co_company_ceb89a_idx')],
                'unique_together': {('referrer', 'company')},
            },
        ),
        migrations.AddIndex(
            model_name='referrer',
            index=models.Index(fields=['last_name', 'first_name'], name='referrers_last_na_fb75ac_idx'),
        ),
        migrations.AddIndex(
            model_name='referrer',
            index=models.Index(fields=['specialty'], name='referrers_special_d14ea0_idx'),
        ),
        migrations.AddIndex(
            model_name='patientreferrer',
            index=models.Index(fields=['patient', 'status'], name='patient_ref_patient_a16da4_idx'),
        ),
        migrations.AddIndex(
            model_name='patientreferrer',
            index=models.Index(fields=['referrer', 'status'], name='patient_ref_referre_dfe6f5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='patientreferrer',
            unique_together={('patient', 'referrer')},
        ),
    ]
