# Generated by Django 4.2.25 on 2025-11-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientreferrer',
            options={'ordering': ['-is_primary', '-referral_date'], 'verbose_name': 'Patient Referrer', 'verbose_name_plural': 'Patient Referrers'},
        ),
        migrations.AddField(
            model_name='patientreferrer',
            name='is_primary',
            field=models.BooleanField(default=False, help_text="Is this the patient's primary/current coordinator/referrer?"),
        ),
        migrations.AddIndex(
            model_name='patientreferrer',
            index=models.Index(fields=['patient', 'is_primary'], name='patient_ref_patient_80077b_idx'),
        ),
    ]
