# Generated by Django 4.2.25 on 2025-11-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrers', '0002_add_is_primary_to_patient_referrer'),
    ]

    operations = [
        migrations.AddField(
            model_name='referrer',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this referrer/coordinator (NDIS notes from FileMaker will be stored here)', null=True),
        ),
    ]
