# Generated by Django 4.2.25 on 2025-10-30 01:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinicians', '0001_initial'),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='XeroConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(help_text='Xero tenant/organisation ID', max_length=255)),
                ('tenant_name', models.CharField(blank=True, max_length=255)),
                ('access_token', models.TextField(help_text='Encrypted access token')),
                ('refresh_token', models.TextField(help_text='Encrypted refresh token')),
                ('id_token', models.TextField(blank=True, help_text='OpenID ID token')),
                ('token_type', models.CharField(default='Bearer', max_length=50)),
                ('expires_at', models.DateTimeField(help_text='When the access token expires')),
                ('scopes', models.TextField(help_text='Space-separated OAuth2 scopes')),
                ('is_active', models.BooleanField(default=True)),
                ('connected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_refresh_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'xero_connections',
                'ordering': ['-connected_at'],
            },
        ),
        migrations.CreateModel(
            name='XeroSyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_type', models.CharField(choices=[('contact_create', 'Contact Created'), ('contact_update', 'Contact Updated'), ('invoice_create', 'Invoice Created'), ('invoice_update', 'Invoice Updated'), ('payment_sync', 'Payment Synced'), ('token_refresh', 'Token Refreshed')], max_length=50)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial Success')], max_length=20)),
                ('request_data', models.JSONField(blank=True, help_text='Request payload (sanitized)', null=True)),
                ('response_data', models.JSONField(blank=True, help_text='Response data', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('local_entity_type', models.CharField(blank=True, max_length=50)),
                ('local_entity_id', models.UUIDField(blank=True, null=True)),
                ('xero_entity_id', models.CharField(blank=True, max_length=255)),
                ('duration_ms', models.IntegerField(blank=True, help_text='Operation duration in milliseconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'xero_sync_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='xero_sync_l_created_acad42_idx'), models.Index(fields=['operation_type', 'status'], name='xero_sync_l_operati_b82d77_idx'), models.Index(fields=['local_entity_type', 'local_entity_id'], name='xero_sync_l_local_e_d39be7_idx')],
            },
        ),
        migrations.CreateModel(
            name='XeroItemMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('local_code', models.CharField(help_text='Local service/product code', max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('xero_item_code', models.CharField(help_text='Xero Item Code', max_length=100)),
                ('xero_account_code', models.CharField(blank=True, help_text='Xero Account Code (e.g., 200)', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Default unit price', max_digits=12)),
                ('tax_rate_name', models.CharField(blank=True, help_text="e.g., 'GST on Income', 'Tax Exempt'", max_length=100)),
                ('tax_type', models.CharField(default='OUTPUT2', help_text='Xero TaxType code', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'xero_item_mappings',
                'indexes': [models.Index(fields=['local_code'], name='xero_item_m_local_c_2fe18c_idx'), models.Index(fields=['xero_item_code'], name='xero_item_m_xero_it_16f945_idx')],
            },
        ),
        migrations.CreateModel(
            name='XeroContactLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('local_type', models.CharField(choices=[('patient', 'Patient'), ('clinician', 'Clinician'), ('referrer', 'Referrer')], max_length=20)),
                ('local_id', models.UUIDField(help_text='FK to local entity (patient/clinician)')),
                ('xero_contact_id', models.CharField(help_text='Xero Contact GUID', max_length=255, unique=True)),
                ('xero_contact_number', models.CharField(blank=True, help_text='Human-readable contact number', max_length=50)),
                ('xero_contact_name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'xero_contact_links',
                'indexes': [models.Index(fields=['local_type', 'local_id'], name='xero_contac_local_t_b9562b_idx'), models.Index(fields=['xero_contact_id'], name='xero_contac_xero_co_302420_idx')],
                'unique_together': {('local_type', 'local_id')},
            },
        ),
        migrations.CreateModel(
            name='XeroTrackingCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracking_category_id', models.CharField(help_text='Xero Tracking Category GUID', max_length=255)),
                ('tracking_option_id', models.CharField(help_text='Xero Tracking Option GUID', max_length=255)),
                ('category_name', models.CharField(help_text="e.g., 'Clinic', 'Location'", max_length=100)),
                ('option_name', models.CharField(help_text="e.g., 'Tamworth', 'Newcastle'", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='xero_tracking', to='clinicians.clinic')),
            ],
            options={
                'db_table': 'xero_tracking_categories',
                'indexes': [models.Index(fields=['clinic'], name='xero_tracki_clinic__5f8214_idx'), models.Index(fields=['tracking_category_id', 'tracking_option_id'], name='xero_tracki_trackin_80d9b4_idx')],
            },
        ),
        migrations.CreateModel(
            name='XeroInvoiceLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('xero_invoice_id', models.CharField(help_text='Xero Invoice GUID', max_length=255, unique=True)),
                ('xero_invoice_number', models.CharField(blank=True, help_text='Human-readable invoice number', max_length=50)),
                ('xero_invoice_type', models.CharField(default='ACCREC', help_text='ACCREC or ACCPAY', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('AUTHORISED', 'Authorised'), ('PAID', 'Paid'), ('VOIDED', 'Voided'), ('DELETED', 'Deleted')], default='DRAFT', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_due', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='AUD', max_length=3)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('fully_paid_on_date', models.DateField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xero_invoices', to='appointments.appointment')),
            ],
            options={
                'db_table': 'xero_invoice_links',
                'indexes': [models.Index(fields=['xero_invoice_id'], name='xero_invoic_xero_in_18f8e7_idx'), models.Index(fields=['status'], name='xero_invoic_status_457597_idx'), models.Index(fields=['appointment'], name='xero_invoic_appoint_a84deb_idx')],
            },
        ),
    ]
