# Generated by Django 4.2.25 on 2025-11-16 04:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('patients', '0009_patient_ndis_plan_end_date_and_more'),
        ('appointments', '0006_add_xero_billing_fields'),
        ('xero_integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='XeroQuoteLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('xero_quote_id', models.CharField(help_text='Xero Quote GUID', max_length=255, unique=True)),
                ('xero_quote_number', models.CharField(blank=True, help_text='Human-readable quote number', max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('INVOICED', 'Invoiced'), ('DELETED', 'Deleted')], default='DRAFT', help_text='Current quote status', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, help_text='Total including tax', max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, help_text='Total before tax', max_digits=12)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, help_text='Total tax amount', max_digits=12)),
                ('currency', models.CharField(default='AUD', max_length=3)),
                ('quote_date', models.DateField(blank=True, help_text='Date quote was created', null=True)),
                ('expiry_date', models.DateField(blank=True, help_text='Quote expiry date', null=True)),
                ('converted_at', models.DateTimeField(blank=True, help_text='When quote was converted to invoice', null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Xero Quote Link',
                'verbose_name_plural': 'Xero Quote Links',
                'db_table': 'xero_quote_links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='xerocontactlink',
            name='xero_contac_local_t_b9562b_idx',
        ),
        migrations.AlterUniqueTogether(
            name='xerocontactlink',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='xerocontactlink',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company linked to Xero contact', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xero_contacts', to='companies.company'),
        ),
        migrations.AddField(
            model_name='xerocontactlink',
            name='connection',
            field=models.ForeignKey(blank=True, help_text='Xero connection this link belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_links', to='xero_integration.xeroconnection'),
        ),
        migrations.AddField(
            model_name='xerocontactlink',
            name='patient',
            field=models.ForeignKey(blank=True, help_text='Patient linked to Xero contact', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xero_contacts', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='xeroinvoicelink',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total before tax', max_digits=12),
        ),
        migrations.AddField(
            model_name='xeroinvoicelink',
            name='total_tax',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total tax amount', max_digits=12),
        ),
        migrations.AlterField(
            model_name='xerocontactlink',
            name='xero_contact_id',
            field=models.CharField(help_text='Xero Contact GUID', max_length=255),
        ),
        migrations.AddIndex(
            model_name='xerocontactlink',
            index=models.Index(fields=['patient'], name='xero_contac_patient_274e2e_idx'),
        ),
        migrations.AddIndex(
            model_name='xerocontactlink',
            index=models.Index(fields=['company'], name='xero_contac_company_303747_idx'),
        ),
        migrations.AddIndex(
            model_name='xerocontactlink',
            index=models.Index(fields=['connection'], name='xero_contac_connect_872fff_idx'),
        ),
        migrations.AddConstraint(
            model_name='xerocontactlink',
            constraint=models.CheckConstraint(check=models.Q(('company__isnull', True), ('patient__isnull', True), _negated=True), name='contact_link_has_patient_or_company'),
        ),
        migrations.AddConstraint(
            model_name='xerocontactlink',
            constraint=models.UniqueConstraint(condition=models.Q(('patient__isnull', False)), fields=('connection', 'patient'), name='unique_patient_per_connection'),
        ),
        migrations.AddConstraint(
            model_name='xerocontactlink',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', False)), fields=('connection', 'company'), name='unique_company_per_connection'),
        ),
        migrations.AddField(
            model_name='xeroquotelink',
            name='appointment',
            field=models.ForeignKey(blank=True, help_text='Appointment this quote is for (if any)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xero_quotes', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='xeroquotelink',
            name='converted_invoice',
            field=models.ForeignKey(blank=True, help_text='Invoice created from this quote', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_quote', to='xero_integration.xeroinvoicelink'),
        ),
        migrations.RemoveField(
            model_name='xerocontactlink',
            name='local_id',
        ),
        migrations.RemoveField(
            model_name='xerocontactlink',
            name='local_type',
        ),
        migrations.AddIndex(
            model_name='xeroquotelink',
            index=models.Index(fields=['xero_quote_id'], name='xero_quote__xero_qu_5404f5_idx'),
        ),
        migrations.AddIndex(
            model_name='xeroquotelink',
            index=models.Index(fields=['status'], name='xero_quote__status_2be8f6_idx'),
        ),
        migrations.AddIndex(
            model_name='xeroquotelink',
            index=models.Index(fields=['appointment'], name='xero_quote__appoint_2bd216_idx'),
        ),
        migrations.AddIndex(
            model_name='xeroquotelink',
            index=models.Index(fields=['-created_at'], name='xero_quote__created_2880a2_idx'),
        ),
    ]
