# Generated by Django 4.2.25 on 2025-11-16 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_add_xero_billing_fields'),
        ('patients', '0009_patient_ndis_plan_end_date_and_more'),
        ('companies', '0001_initial'),
        ('xero_integration', '0002_add_xero_billing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='xeroinvoicelink',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this invoice is billed to (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xero_invoices', to='companies.company'),
        ),
        migrations.AddField(
            model_name='xeroinvoicelink',
            name='patient',
            field=models.ForeignKey(blank=True, help_text='Patient this invoice is for (required if no appointment)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xero_invoices', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='xeroinvoicelink',
            name='appointment',
            field=models.ForeignKey(blank=True, help_text='Optional: Link to appointment if invoice is for a service', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xero_invoices', to='appointments.appointment'),
        ),
        migrations.AddIndex(
            model_name='xeroinvoicelink',
            index=models.Index(fields=['patient'], name='xero_invoic_patient_f4b3b4_idx'),
        ),
        migrations.AddIndex(
            model_name='xeroinvoicelink',
            index=models.Index(fields=['company'], name='xero_invoic_company_ee797d_idx'),
        ),
    ]
