# Generated by Django 4.2.25 on 2025-11-16 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('patients', '0009_patient_ndis_plan_end_date_and_more'),
        ('xero_integration', '0003_xeroinvoicelink_company_xeroinvoicelink_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='xeroquotelink',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this quote is billed to (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xero_quotes', to='companies.company'),
        ),
        migrations.AddField(
            model_name='xeroquotelink',
            name='patient',
            field=models.ForeignKey(blank=True, help_text='Patient this quote is for (service recipient)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xero_quotes', to='patients.patient'),
        ),
        migrations.AddIndex(
            model_name='xeroquotelink',
            index=models.Index(fields=['patient'], name='xero_quote__patient_2dc6b3_idx'),
        ),
        migrations.AddIndex(
            model_name='xeroquotelink',
            index=models.Index(fields=['company'], name='xero_quote__company_c2283b_idx'),
        ),
    ]
