# Generated by Django 4.2.25 on 2025-11-18 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xero_integration', '0004_xeroquotelink_company_xeroquotelink_patient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='XeroBatchPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_reference', models.CharField(max_length=255)),
                ('payment_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_count', models.IntegerField()),
                ('account_code', models.CharField(max_length=50)),
                ('remittance_file', models.FileField(blank=True, null=True, upload_to='remittance_advice/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_payments', to='xero_integration.xeroconnection')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'xero_batch_payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='XeroPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('xero_payment_id', models.CharField(max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('account_code', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('AUTHORISED', 'Authorised'), ('DELETED', 'Deleted')], default='AUTHORISED', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('batch_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='xero_integration.xerobatchpayment')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='xero_integration.xeroconnection')),
                ('invoice_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='xero_integration.xeroinvoicelink')),
            ],
            options={
                'db_table': 'xero_payments',
                'ordering': ['-payment_date', '-created_at'],
                'indexes': [models.Index(fields=['connection', 'payment_date'], name='xero_paymen_connect_79b68b_idx'), models.Index(fields=['invoice_link'], name='xero_paymen_invoice_023dc9_idx'), models.Index(fields=['batch_payment'], name='xero_paymen_batch_p_f639c2_idx'), models.Index(fields=['xero_payment_id'], name='xero_paymen_xero_pa_25e375_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='xerobatchpayment',
            index=models.Index(fields=['connection', 'payment_date'], name='xero_batch__connect_a327d7_idx'),
        ),
        migrations.AddIndex(
            model_name='xerobatchpayment',
            index=models.Index(fields=['batch_reference'], name='xero_batch__batch_r_6fa597_idx'),
        ),
    ]
