# Generated by Django 4.2.25 on 2025-11-19 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinicians', '0006_change_professional_url_to_charfield'),
        ('xero_integration', '0005_xerobatchpayment_xeropayment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='xeroinvoicelink',
            name='clinician',
            field=models.ForeignKey(blank=True, help_text='Clinician who created or sent this invoice (for email signature)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invoices', to='clinicians.clinician'),
        ),
        migrations.AddIndex(
            model_name='xeroinvoicelink',
            index=models.Index(fields=['clinician'], name='xero_invoic_clinici_35d368_idx'),
        ),
    ]
