# Generated by Django 4.2.25 on 2025-11-08 23:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0005_patient_plan_dates_json_alter_patient_plan_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text="Coordinator's first name", max_length=100)),
                ('last_name', models.CharField(help_text="Coordinator's last name", max_length=100)),
                ('organization', models.CharField(blank=True, help_text='Organization (e.g., Ability Connect, Afford)', max_length=200, null=True)),
                ('coordinator_type', models.CharField(choices=[('SUPPORT_COORDINATOR', 'Support Coordinator'), ('LAC', 'LAC (Local Area Coordinator)'), ('PLAN_MANAGER', 'Plan Manager')], default='SUPPORT_COORDINATOR', help_text='Type of coordinator', max_length=50)),
                ('contact_json', models.JSONField(blank=True, default=dict, help_text='Contact details (phone, email, mobile)', null=True)),
                ('address_json', models.JSONField(blank=True, default=dict, help_text='Address details', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Coordinator',
                'verbose_name_plural': 'Coordinators',
                'db_table': 'coordinators',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='PatientCoordinator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assignment_date', models.DateField(help_text='Date coordinator was assigned to patient')),
                ('end_date', models.DateField(blank=True, help_text='Date assignment ended (null if still current)', null=True)),
                ('is_current', models.BooleanField(default=True, help_text='Is this the current coordinator?')),
                ('ndis_plan_start', models.DateField(blank=True, help_text='NDIS plan start date for this coordinator period', null=True)),
                ('ndis_plan_end', models.DateField(blank=True, help_text='NDIS plan end date for this coordinator period', null=True)),
                ('ndis_notes', models.TextField(blank=True, help_text='Notes specific to this coordinator assignment period', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coordinator', models.ForeignKey(help_text='Coordinator assigned to patient', on_delete=django.db.models.deletion.PROTECT, related_name='patient_coordinators', to='coordinators.coordinator')),
                ('patient', models.ForeignKey(help_text='Patient being coordinated', on_delete=django.db.models.deletion.CASCADE, related_name='patient_coordinators', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Patient Coordinator',
                'verbose_name_plural': 'Patient Coordinators',
                'db_table': 'patient_coordinators',
                'ordering': ['-is_current', '-assignment_date'],
            },
        ),
        migrations.AddIndex(
            model_name='coordinator',
            index=models.Index(fields=['last_name', 'first_name'], name='coordinator_last_na_fceee5_idx'),
        ),
        migrations.AddIndex(
            model_name='coordinator',
            index=models.Index(fields=['organization'], name='coordinator_organiz_34df2f_idx'),
        ),
        migrations.AddIndex(
            model_name='patientcoordinator',
            index=models.Index(fields=['patient', 'is_current'], name='patient_coo_patient_d0f0db_idx'),
        ),
        migrations.AddIndex(
            model_name='patientcoordinator',
            index=models.Index(fields=['coordinator', 'is_current'], name='patient_coo_coordin_aeffa2_idx'),
        ),
        migrations.AddIndex(
            model_name='patientcoordinator',
            index=models.Index(fields=['assignment_date'], name='patient_coo_assignm_d987bf_idx'),
        ),
    ]
