# Generated by Django 4.2.25 on 2025-11-05 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('name', models.CharField(help_text="Auto-generated or custom batch name (e.g., 'Pre-Surgery Photos', 'Uploaded 5 Nov 2025')", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description of this batch')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('image_count', models.IntegerField(default=0, help_text='Number of images in this batch')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'images_batch',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('s3_key', models.CharField(help_text='S3 object key (path in bucket)', max_length=500)),
                ('s3_thumbnail_key', models.CharField(blank=True, help_text='S3 key for thumbnail (optional)', max_length=500)),
                ('original_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(default='image/jpeg', max_length=100)),
                ('width', models.IntegerField(blank=True, help_text='Image width in pixels', null=True)),
                ('height', models.IntegerField(blank=True, help_text='Image height in pixels', null=True)),
                ('category', models.CharField(choices=[('medical', 'Medical Records'), ('prescription', 'Prescription'), ('referral', 'Referral Letter'), ('xray', 'X-Ray / Imaging'), ('invoice', 'Invoice'), ('quote', 'Quote'), ('consent', 'Consent Form'), ('insurance', 'Insurance Document'), ('dorsal', 'Dorsal'), ('plantar', 'Plantar'), ('posterior', 'Posterior'), ('anterior', 'Anterior'), ('medial', 'Medial'), ('lateral', 'Lateral'), ('wound', 'Wound'), ('right_leg', 'Right Leg'), ('left_leg', 'Left Leg'), ('l_brannock', 'L-Brannock'), ('r_brannock', 'R-Brannock'), ('r_mfoot_length', 'R-MFoot Length'), ('r_mfoot_width', 'R-MFoot Width'), ('l_mfoot_length', 'L-MFoot Length'), ('l_mfoot_width', 'L-MFoot Width'), ('casts', 'Casts'), ('left_lat', 'Left Lat'), ('right_lat', 'Right Lat'), ('r_shoe', 'R-Shoe'), ('l_shoe', 'L-Shoe'), ('afo', 'AFO'), ('x_ray_doc', 'X-Ray (Document)'), ('cmo', 'CMO'), ('other', 'Other')], default='other', max_length=50)),
                ('caption', models.TextField(blank=True, help_text='Optional caption/notes')),
                ('date_taken', models.DateField(blank=True, help_text='Date photo was taken', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(default=0, help_text='Display order within batch')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='images.imagebatch')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'images_image',
                'ordering': ['batch', 'order', 'uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='imagebatch',
            index=models.Index(fields=['content_type', 'object_id'], name='images_batc_content_0f81d4_idx'),
        ),
        migrations.AddIndex(
            model_name='imagebatch',
            index=models.Index(fields=['uploaded_at'], name='images_batc_uploade_65f7d1_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['batch', 'order'], name='images_imag_batch_i_4f6c72_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['uploaded_at'], name='images_imag_uploade_c79a44_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['category'], name='images_imag_categor_b411cf_idx'),
        ),
    ]
