# Generated by Django 4.2.25 on 2025-11-05 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumbnail_size',
            field=models.IntegerField(blank=True, help_text='Thumbnail file size in bytes', null=True),
        ),
    ]
