# Generated by Django 4.2.25 on 2025-11-10 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_add_thumbnail_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='filemaker_id',
            field=models.UUIDField(blank=True, help_text='Original FileMaker image ID (from API_Images.id) - for imported images only', null=True, unique=True),
        ),
    ]
