# Generated by Django 4.2.25 on 2025-11-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_image_filemaker_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.CharField(blank=True, default='', help_text='Image category/type (flexible text field - can be standard category or custom)', max_length=100),
        ),
    ]
