# Generated by Django 4.2.25 on 2025-11-15 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_image_filemaker_id 2'),
        ('images', '0004_remove_category_choices'),
        ('images', '0004_remove_category_choices 2'),
    ]

    operations = [
    ]
