"""
Django settings for ncc_api project.

Generated by 'django-admin startproject' using Django 4.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-jnxev3%%fdaf&1_x2vn63gt(8yv4o8uqw0g3wzx_=asrpn)8t!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']  # Allow all hosts for webhook testing (Cloudflare Tunnel domains)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Required for allauth
    'rest_framework',
    'corsheaders',
    'django_filters',
    'django_extensions',
    # Allauth apps
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    # Project apps
    'patients',
    'appointments',
    'clinicians',
    'xero_integration',
    'sms_integration',
    'gmail_integration',
    'documents',
    'ai_services',  # S3 document storage
    'settings',  # Settings management (Funding Sources, etc.)
    'reminders',  # Reminders for calendar waiting list
    'notes',  # Patient notes (clinical notes, clinic dates, etc.)
    'images',  # Patient images (photos, x-rays, etc.)
    'letters',  # Patient letters (correspondence, support letters, etc.)
    'invoices',  # Invoice PDF generation
    # FileMaker migration apps
    'referrers',  # Medical referrers (GPs, specialists, etc.)
    'coordinators',  # NDIS Support Coordinators and LAC
    'companies',  # Medical practices, NDIS providers
    'contacts',  # General contacts and contact relationships
    'data_management',  # Data management and FileMaker reimport
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # Allauth middleware
]

ROOT_URLCONF = 'ncc_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ncc_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-au'  # Australian English

TIME_ZONE = 'Australia/Sydney'  # Australian Eastern Time (handles daylight saving automatically)

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS settings - allow frontend to access API
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://localhost:3000",
    "https://127.0.0.1:3000",
    "https://localhost:8000",
    "https://127.0.0.1:8000",
]

CORS_ALLOW_CREDENTIALS = True

# CSRF settings for HTTPS
CSRF_TRUSTED_ORIGINS = [
    "https://localhost:3000",
    "https://127.0.0.1:3000",
    "https://localhost:8000",
    "https://127.0.0.1:8000",
]

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',  # For browser-based auth
        'rest_framework.authentication.BasicAuthentication',  # Fallback
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',  # Change to IsAuthenticated in production
        # Note: SMS patient endpoints explicitly use IsAuthenticated for security
    ],
}

# Django Allauth Configuration
SITE_ID = 1  # Required for allauth

AUTHENTICATION_BACKENDS = [
    # Django default authentication (username/password)
    'django.contrib.auth.backends.ModelBackend',
    # Allauth authentication (social accounts)
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Allauth settings
ACCOUNT_LOGIN_METHODS = {'email'}  # Use email for login
ACCOUNT_SIGNUP_FIELDS = ['email*']  # Only require email for signup
ACCOUNT_EMAIL_VERIFICATION = 'none'  # Set to 'mandatory' in production
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_ADAPTER = 'allauth.account.adapter.DefaultAccountAdapter'
SOCIALACCOUNT_ADAPTER = 'gmail_integration.adapters.GmailSocialAccountAdapter'  # Custom adapter to link Google OAuth login with Gmail

# OAuth Provider Settings (django-allauth uses "SOCIALACCOUNT" prefix for OAuth providers)
# Note: "SOCIALACCOUNT" is django-allauth's terminology for OAuth providers (Google, Microsoft, etc.)
# It's used for business authentication, not just social media logins
SOCIALACCOUNT_LOGIN_ON_GET = True  # Skip intermediate "Sign In Via Google" page - start OAuth immediately on GET
SOCIALACCOUNT_AUTO_SIGNUP = True  # Automatically create user account on first login
SOCIALACCOUNT_QUERY_EMAIL = True  # Request email from OAuth provider
SOCIALACCOUNT_EMAIL_REQUIRED = True  # Require email for OAuth accounts
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'  # Skip email verification for OAuth accounts

# Google OAuth Provider Settings
# Reuse the same OAuth credentials as Gmail integration for unified login
# These should be set in .env file (same as Gmail):
# GMAIL_CLIENT_ID=your_client_id (or GOOGLE_OAUTH2_CLIENT_ID)
# GMAIL_CLIENT_SECRET=your_client_secret (or GOOGLE_OAUTH2_CLIENT_SECRET)
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
            'https://www.googleapis.com/auth/gmail.send',  # Gmail API scope for email sending
            'https://www.googleapis.com/auth/gmail.readonly',  # Gmail API scope for reading
        ],
        'AUTH_PARAMS': {
            'access_type': 'offline',  # Get refresh token for Gmail API
            'prompt': 'consent',  # Force consent to get refresh token
        },
        # Note: APP credentials are stored in database (SocialApp model)
        # Remove APP config here to use database SocialApp instead
    }
}

# Login/Logout URLs
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'  # Will redirect to frontend via login_redirect view
LOGOUT_REDIRECT_URL = 'https://localhost:3000/login/'

# Xero Integration Settings
XERO_CLIENT_ID = os.getenv('XERO_CLIENT_ID')
XERO_CLIENT_SECRET = os.getenv('XERO_CLIENT_SECRET')
XERO_REDIRECT_URI = os.getenv('XERO_REDIRECT_URI', 'https://localhost:8000/xero/oauth/callback/')
