# Generated by Django 4.2.25 on 2025-10-30 00:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Clinic name (e.g., 'Walk Easy Tamworth')", max_length=200)),
                ('abn', models.CharField(blank=True, help_text='Australian Business Number', max_length=20, null=True, verbose_name='ABN')),
                ('phone', models.CharField(blank=True, help_text='Main clinic phone number', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, help_text='Main clinic email address', max_length=254, null=True)),
                ('address_json', models.JSONField(blank=True, default=dict, help_text='Clinic address (JSON format)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Clinic',
                'verbose_name_plural': 'Clinics',
                'db_table': 'clinics',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Clinician',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(help_text="Clinician's full name", max_length=200)),
                ('credential', models.CharField(blank=True, help_text="Professional credentials (e.g., 'C.Ped CM Au')", max_length=100, null=True)),
                ('email', models.EmailField(blank=True, help_text="Clinician's email address", max_length=254, null=True)),
                ('phone', models.CharField(blank=True, help_text="Clinician's phone number", max_length=20, null=True)),
                ('role', models.CharField(blank=True, choices=[('PEDORTHIST', 'Pedorthist'), ('ADMIN', 'Administrator'), ('RECEPTION', 'Reception'), ('MANAGER', 'Manager'), ('OTHER', 'Other')], help_text="Clinician's role in the organization", max_length=50, null=True)),
                ('active', models.BooleanField(default=True, help_text='Is the clinician currently active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(blank=True, help_text='Primary clinic location', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinicians', to='clinicians.clinic')),
            ],
            options={
                'verbose_name': 'Clinician',
                'verbose_name_plural': 'Clinicians',
                'db_table': 'clinicians',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['active', 'full_name'], name='clinicians_active_1382ea_idx'), models.Index(fields=['clinic', 'active'], name='clinicians_clinic__d81194_idx')],
            },
        ),
    ]
