# Generated by Django 4.2.25 on 2025-11-08 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicians', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='filemaker_id',
            field=models.UUIDField(blank=True, help_text='Original FileMaker clinic ID (for import tracking)', null=True, unique=True),
        ),
    ]
