# Generated by Django 4.2.25 on 2025-11-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicians', '0002_add_filemaker_id_to_clinic'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='color',
            field=models.CharField(blank=True, default='#3B82F6', help_text="Hex color code for calendar display (e.g., '#3B82F6')", max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='sms_reminder_template',
            field=models.TextField(blank=True, help_text='SMS reminder template for this clinic (use {patient_name}, {date}, {time}, {clinic_name} placeholders)', null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='sms_reminders_enabled',
            field=models.BooleanField(default=True, help_text='Whether automatic SMS reminders are enabled for this clinic'),
        ),
    ]
