# Generated by Django 4.2.25 on 2025-11-15 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicians', '0003_clinic_color_clinic_sms_reminder_template_and_more'),
        ('clinicians', '0003_clinic_color_clinic_sms_reminder_template_and_more 2'),
    ]

    operations = [
    ]
