# Generated by Django 4.2.25 on 2025-11-17 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinicians', '0004_merge_20251116_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinician',
            name='professional_body_url',
            field=models.URLField(blank=True, help_text="Professional body website (e.g., 'www.pedorthics.org.au')", null=True),
        ),
        migrations.AddField(
            model_name='clinician',
            name='registration_number',
            field=models.CharField(blank=True, help_text="Professional registration number (e.g., 'Pedorthic Registration # 3454')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clinician',
            name='signature_html',
            field=models.TextField(blank=True, help_text='HTML signature for emails (rich text format)', null=True),
        ),
        migrations.AddField(
            model_name='clinician',
            name='signature_image',
            field=models.CharField(blank=True, help_text='S3 key for signature image (used in letters and PDFs)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='clinician',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Link to Django User account (for Google OAuth login)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinician_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
