# Generated by Django 4.2.25 on 2025-11-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicians', '0005_clinician_professional_body_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinician',
            name='professional_body_url',
            field=models.CharField(blank=True, help_text="Professional body website (e.g., 'www.pedorthics.org.au')", max_length=200, null=True),
        ),
    ]
