# Generated by Django 4.2.25 on 2025-11-03 22:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FundingSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Funding source name (e.g., 'NDIS', 'Private', 'DVA')", max_length=100)),
                ('code', models.CharField(blank=True, help_text="Optional short code (e.g., 'NDIS', 'PRV', 'DVA')", max_length=20, null=True)),
                ('active', models.BooleanField(default=True, help_text='Whether this funding source is active')),
                ('order', models.IntegerField(default=0, help_text='Order for sorting in dropdowns')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Funding Source',
                'verbose_name_plural': 'Funding Sources',
                'db_table': 'funding_sources',
                'ordering': ['order', 'name'],
            },
        ),
    ]
