# Generated by Django 4.2.25 on 2025-10-30 17:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('file_name', models.CharField(max_length=255)),
                ('original_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(max_length=100)),
                ('s3_bucket', models.CharField(max_length=255)),
                ('s3_key', models.CharField(help_text='S3 object key/path', max_length=512)),
                ('s3_url', models.URLField(blank=True, help_text='Pre-signed or public URL', max_length=1024)),
                ('category', models.CharField(choices=[('medical', 'Medical Records'), ('prescription', 'Prescription'), ('referral', 'Referral Letter'), ('xray', 'X-Ray / Imaging'), ('invoice', 'Invoice'), ('quote', 'Quote'), ('consent', 'Consent Form'), ('insurance', 'Insurance Document'), ('other', 'Other')], default='other', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('uploaded_by', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='documents_d_content_ba3031_idx'), models.Index(fields=['category'], name='documents_d_categor_2c6923_idx'), models.Index(fields=['uploaded_at'], name='documents_d_uploade_65506e_idx')],
            },
        ),
    ]
