# Generated by Django 4.2.25 on 2025-10-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_content_type_alter_document_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('medical', 'Medical Records'), ('prescription', 'Prescription'), ('referral', 'Referral Letter'), ('xray', 'X-Ray / Imaging'), ('invoice', 'Invoice'), ('quote', 'Quote'), ('consent', 'Consent Form'), ('insurance', 'Insurance Document'), ('dorsal', 'Dorsal'), ('plantar', 'Plantar'), ('posterior', 'Posterior'), ('anterior', 'Anterior'), ('medial', 'Medial'), ('lateral', 'Lateral'), ('wound', 'Wound'), ('right_leg', 'Right Leg'), ('left_leg', 'Left Leg'), ('l_brannock', 'L-Brannock'), ('r_brannock', 'R-Brannock'), ('r_mfoot_length', 'R-MFoot Length'), ('r_mfoot_width', 'R-MFoot Width'), ('l_mfoot_length', 'L-MFoot Length'), ('l_mfoot_width', 'L-MFoot Width'), ('casts', 'Casts'), ('left_lat', 'Left Lat'), ('right_lat', 'Right Lat'), ('r_shoe', 'R-Shoe'), ('l_shoe', 'L-Shoe'), ('afo', 'AFO'), ('x_ray', 'X-Ray'), ('cmo', 'CMO'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
