# Generated by Django 4.2.25 on 2025-11-09 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_add_document_date_and_update_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='filemaker_id',
            field=models.UUIDField(blank=True, help_text='Original FileMaker document ID (from API_Docs.id) - for imported documents only', null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['filemaker_id'], name='documents_d_filemak_c0f910_idx'),
        ),
    ]
