# Generated by Django 4.2.25 on 2025-11-13 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_filemaker_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(blank=True, default='', help_text='Document category/type (flexible text field - can be standard category or custom)', max_length=100),
        ),
    ]
