# Generated by Django 4.2.25 on 2025-11-14 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_remove_category_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='filemaker_metadata',
            field=models.JSONField(blank=True, help_text='FileMaker import metadata (filemaker_clinic, xero_contact_id, imported_at, etc.)', null=True),
        ),
    ]
