# Generated by Django 4.2.25 on 2025-11-14 01:12

from django.db import migrations
import json
import re


def migrate_filemaker_metadata(apps, schema_editor):
    """
    Move FileMaker metadata from description field to filemaker_metadata JSON field.
    
    Example description content:
    {"filemaker_id": "19ACA9D7-013D-4703-9E6D-94762E004892", "filemaker_clinic": "Tamworth", 
     "xero_contact_id": "156dddc2-3ab5-4d71-878a-ab2ddafcc6bb", "imported_at": "2025-11-09T10:46:21.976377"}
    """
    Document = apps.get_model('documents', 'Document')
    
    # Find all documents with JSON-like content in description
    for doc in Document.objects.filter(filemaker_id__isnull=False):
        if not doc.description:
            continue
            
        # Try to parse the description as JSON
        try:
            # Check if description looks like JSON
            if doc.description.strip().startswith('{') and doc.description.strip().endswith('}'):
                metadata = json.loads(doc.description)
                
                # Move to filemaker_metadata field
                doc.filemaker_metadata = metadata
                
                # Clear the description (or keep it if you want)
                doc.description = ''
                
                doc.save(update_fields=['filemaker_metadata', 'description'])
                
                print(f"Migrated FileMaker metadata for document {doc.id}")
        except json.JSONDecodeError:
            # Description is not valid JSON, skip it
            print(f"Skipping document {doc.id} - description is not valid JSON")
            continue


def reverse_migrate_filemaker_metadata(apps, schema_editor):
    """
    Reverse migration: move filemaker_metadata back to description
    """
    Document = apps.get_model('documents', 'Document')
    
    for doc in Document.objects.filter(filemaker_metadata__isnull=False):
        if doc.filemaker_metadata:
            doc.description = json.dumps(doc.filemaker_metadata)
            doc.filemaker_metadata = None
            doc.save(update_fields=['filemaker_metadata', 'description'])


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_add_filemaker_metadata'),
    ]

    operations = [
        migrations.RunPython(migrate_filemaker_metadata, reverse_migrate_filemaker_metadata),
    ]

