# Generated by Django 4.2.25 on 2025-11-15 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_filemaker_id_and_more 2'),
        ('documents', '0006_remove_category_choices 2'),
        ('documents', '0007_add_filemaker_metadata 2'),
        ('documents', '0008_migrate_filemaker_data_from_description'),
        ('documents', '0008_migrate_filemaker_data_from_description 2'),
    ]

    operations = [
    ]
