# Generated by Django 4.2.25 on 2025-11-19 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailGlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_gmail_account', models.EmailField(blank=True, help_text='Default Gmail account to send from', max_length=254, null=True)),
                ('reply_to_email', models.EmailField(blank=True, help_text='Reply-to address (if different from sender)', max_length=254, null=True)),
                ('bcc_all_to', models.EmailField(blank=True, help_text='BCC all emails to this address', max_length=254, null=True)),
                ('clinic_name', models.CharField(default='WalkEasy Nexus', max_length=255)),
                ('clinic_phone', models.CharField(blank=True, max_length=50)),
                ('clinic_email', models.EmailField(blank=True, max_length=254)),
                ('clinic_website', models.URLField(blank=True)),
                ('clinic_address', models.TextField(blank=True)),
                ('clinic_abn', models.CharField(blank=True, max_length=20, verbose_name='ABN')),
                ('clinic_acn', models.CharField(blank=True, max_length=20, verbose_name='ACN')),
                ('bank_account_name', models.CharField(default='WalkEasy Nexus Pty Ltd', max_length=255)),
                ('bank_bsb', models.CharField(blank=True, max_length=10, verbose_name='BSB')),
                ('bank_account_number', models.CharField(blank=True, max_length=20)),
                ('payment_instructions_text', models.TextField(blank=True, help_text='Additional payment instructions')),
                ('payment_reference_format', models.CharField(default='invoice_number', help_text='Format for payment reference', max_length=50)),
                ('confidentiality_notice', models.TextField(default='This email and any attachments are confidential and may contain privileged information.', help_text='Confidentiality notice for email footer')),
                ('default_email_width', models.CharField(default='600px', help_text='Default email width (e.g., 600px, 100%)', max_length=10)),
                ('show_logo', models.BooleanField(default=True, help_text='Show clinic logo in email header')),
                ('show_contact_info', models.BooleanField(default=True, help_text='Show contact info in footer')),
                ('show_payment_instructions', models.BooleanField(default=True, help_text='Show payment instructions in invoice/receipt emails')),
                ('show_bank_details', models.BooleanField(default=True, help_text='Show bank details in invoice/receipt emails')),
                ('show_confidentiality', models.BooleanField(default=True, help_text='Show confidentiality notice in footer')),
                ('auto_send_invoices', models.BooleanField(default=False)),
                ('auto_send_receipts', models.BooleanField(default=False)),
                ('auto_send_quotes', models.BooleanField(default=False)),
                ('send_payment_reminders', models.BooleanField(default=False)),
                ('send_overdue_notices', models.BooleanField(default=False)),
                ('reminder_days_before', models.JSONField(blank=True, default=list, help_text='Days before due date to send reminders (e.g., [7, 3, 1])')),
                ('overdue_days_after', models.JSONField(blank=True, default=list, help_text='Days after due date to send overdue notices (e.g., [7, 14, 30])')),
                ('require_confirmation', models.BooleanField(default=True, help_text='Require confirmation before auto-sending')),
                ('business_hours_only', models.BooleanField(default=False, help_text='Only send emails during business hours')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Global Settings',
                'verbose_name_plural': 'Email Global Settings',
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name (e.g., "Referral Letter", "Overdue Invoice")', max_length=100)),
                ('category', models.CharField(choices=[('invoice', 'Invoice'), ('receipt', 'Receipt'), ('quote', 'Quote'), ('at_report', 'AT Report'), ('letter', 'Letter')], db_index=True, max_length=20)),
                ('description', models.TextField(blank=True, help_text='Internal note about when to use this template')),
                ('subject', models.CharField(help_text='Email subject line. Use tokens like {patient_name}, {invoice_number}', max_length=255)),
                ('body_html', models.TextField(help_text='HTML email body. Supports tokens.')),
                ('body_text', models.TextField(blank=True, help_text='Plain text version (optional, auto-generated if empty)')),
                ('header_color', models.CharField(default='#10b981', help_text='Hex color for email header (e.g., #10b981)', max_length=7)),
                ('is_default', models.BooleanField(default=False, help_text='Default template for this category')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive templates are hidden but not deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_email_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'ordering': ['category', '-is_default', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
    ]
