# Generated by Django 4.2.25 on 2025-11-19 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailglobalsettings',
            name='company_signature_email',
            field=models.EmailField(default='info@walkeasy.com.au', help_text='Email address that uses the company signature', max_length=254),
        ),
        migrations.AddField(
            model_name='emailglobalsettings',
            name='company_signature_html',
            field=models.TextField(blank=True, help_text='Company email signature for info@walkeasy.com.au (HTML format)'),
        ),
        migrations.AddField(
            model_name='emailglobalsettings',
            name='use_email_signatures',
            field=models.BooleanField(default=True, help_text='Automatically append signatures to emails (company or user signatures)'),
        ),
    ]
