# Generated by Django 4.2.25 on 2025-11-20 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_emailglobalsettings_company_signature_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailglobalsettings',
            name='dva_number',
            field=models.CharField(blank=True, default='682730', help_text='DVA account number (e.g., 682730)', max_length=100),
        ),
        migrations.AddField(
            model_name='emailglobalsettings',
            name='enable_number',
            field=models.CharField(blank=True, default='508809', help_text='Enable vendor number (e.g., 508809)', max_length=100),
        ),
        migrations.AddField(
            model_name='emailglobalsettings',
            name='header_color',
            field=models.CharField(default='#5b95cf', help_text='Default header color for emails (hex code, e.g., #5b95cf)', max_length=7),
        ),
        migrations.AddField(
            model_name='emailglobalsettings',
            name='provider_registration_number',
            field=models.CharField(blank=True, default='4050009706', help_text='NDIS/Medicare provider registration number (e.g., 4050009706)', max_length=100),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='header_color',
            field=models.CharField(default='#5b95cf', help_text='Hex color for email header (e.g., #5b95cf)', max_length=7),
        ),
    ]
