# Generated by Django 4.2.25 on 2025-11-20 04:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_emailglobalsettings_dva_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFundingSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Funding source name (e.g., 'HCF', 'WorkCover')", max_length=100, unique=True)),
                ('reference_number', models.CharField(blank=True, help_text="Account/vendor number for this funding source (e.g., '123456')", max_length=100)),
                ('display_format', models.CharField(blank=True, help_text="How to display on invoice (e.g., 'HCF Member #'). Leave blank for default: '[Name] - [Patient Name]'", max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this funding source is currently active')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this funding source')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Custom Funding Source',
                'verbose_name_plural': 'Custom Funding Sources',
                'db_table': 'custom_funding_sources',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='custom_fund_is_acti_23d755_idx'), models.Index(fields=['name'], name='custom_fund_name_9e9078_idx')],
            },
        ),
    ]
