# Generated by Django 4.2.25 on 2025-11-08 23:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Company/practice name', max_length=200)),
                ('abn', models.CharField(blank=True, help_text='Australian Business Number', max_length=20, null=True, verbose_name='ABN')),
                ('contact_json', models.JSONField(blank=True, default=dict, help_text='Contact details (phone, email, fax)', null=True)),
                ('address_json', models.JSONField(blank=True, default=dict, help_text='Address details', null=True)),
                ('company_type', models.CharField(choices=[('MEDICAL_PRACTICE', 'Medical Practice'), ('NDIS_PROVIDER', 'NDIS Provider'), ('OTHER', 'Other')], default='MEDICAL_PRACTICE', help_text='Type of company/organization', max_length=50)),
                ('filemaker_id', models.UUIDField(blank=True, help_text='Original FileMaker company ID (for import tracking)', null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'companies',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='companies_name_c7a1b3_idx'), models.Index(fields=['company_type'], name='companies_company_b23eb3_idx')],
            },
        ),
    ]
