# Generated by Django 4.2.25 on 2025-10-30 05:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Template name (e.g., 'appointment_reminder')", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='What this template is used for')),
                ('message_template', models.TextField(help_text='Template text. Use {patient_name}, {appointment_date}, {appointment_time}, {clinic_name}, {clinician_name}')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sms_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SMSMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(help_text='Recipient phone number (E.164 format preferred)', max_length=20)),
                ('message', models.TextField(help_text='Message content (max 160 chars per SMS)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('external_message_id', models.CharField(blank=True, help_text='Message ID from SMS provider', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='When to send this message (for scheduled sends)', null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error details if sending failed')),
                ('retry_count', models.IntegerField(default=0, help_text='Number of send attempts')),
                ('sms_count', models.IntegerField(default=1, help_text='Number of SMS segments (messages > 160 chars use multiple)')),
                ('cost', models.DecimalField(blank=True, decimal_places=4, help_text='Cost in AUD', max_digits=6, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes')),
                ('appointment', models.ForeignKey(blank=True, help_text='Related appointment (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_messages', to='appointments.appointment')),
                ('patient', models.ForeignKey(help_text='Patient this message is for', on_delete=django.db.models.deletion.CASCADE, related_name='sms_messages', to='patients.patient')),
                ('template', models.ForeignKey(blank=True, help_text='Template used to generate this message', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms_integration.smstemplate')),
            ],
            options={
                'db_table': 'sms_messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', '-created_at'], name='sms_message_patient_7de4fd_idx'), models.Index(fields=['appointment'], name='sms_message_appoint_b0f994_idx'), models.Index(fields=['status', 'scheduled_at'], name='sms_message_status_e6ced5_idx'), models.Index(fields=['-created_at'], name='sms_message_created_66bff0_idx')],
            },
        ),
        migrations.CreateModel(
            name='SMSInbound',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_number', models.CharField(help_text='Sender phone number', max_length=20)),
                ('to_number', models.CharField(help_text='Our number that received the message', max_length=20)),
                ('message', models.TextField(help_text='Received message content')),
                ('external_message_id', models.CharField(blank=True, help_text='Message ID from SMS provider', max_length=100)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_processed', models.BooleanField(default=False, help_text='Has this been reviewed/handled?')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_by', models.CharField(blank=True, help_text='Staff member who processed', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Processing notes')),
                ('patient', models.ForeignKey(blank=True, help_text='Matched patient (if found)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_received', to='patients.patient')),
            ],
            options={
                'db_table': 'sms_inbound',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['from_number', '-received_at'], name='sms_inbound_from_nu_db1ff5_idx'), models.Index(fields=['is_processed', '-received_at'], name='sms_inbound_is_proc_e928ed_idx'), models.Index(fields=['-received_at'], name='sms_inbound_receive_646d41_idx')],
            },
        ),
    ]
