# Generated by Django 4.2.25 on 2025-10-30 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('sms_integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsmessage',
            name='patient',
            field=models.ForeignKey(blank=True, help_text='Patient this message is for (optional for ad-hoc messages)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_messages', to='patients.patient'),
        ),
    ]
