# Generated by Django 4.2.25 on 2025-11-08 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_integration', '0002_alter_smsmessage_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsinbound',
            name='download_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('downloaded', 'Downloaded'), ('failed', 'Failed')], help_text='Status of media download from provider to our S3', max_length=20),
        ),
        migrations.AddField(
            model_name='smsinbound',
            name='has_media',
            field=models.BooleanField(default=False, help_text='Does this message include media (image)?'),
        ),
        migrations.AddField(
            model_name='smsinbound',
            name='media_downloaded_url',
            field=models.URLField(blank=True, help_text='Our S3 URL after downloading media', max_length=1024),
        ),
        migrations.AddField(
            model_name='smsinbound',
            name='media_size',
            field=models.IntegerField(blank=True, help_text='Media file size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='smsinbound',
            name='media_type',
            field=models.CharField(blank=True, help_text='MIME type (e.g., image/jpeg, image/png)', max_length=50),
        ),
        migrations.AddField(
            model_name='smsinbound',
            name='media_url',
            field=models.URLField(blank=True, help_text="Provider's URL for media file (SMS Broadcast's server)", max_length=1024),
        ),
        migrations.AddField(
            model_name='smsinbound',
            name='s3_key',
            field=models.CharField(blank=True, help_text='S3 object key (path in bucket: mms/inbound/)', max_length=500),
        ),
    ]
