# Generated by Django 4.2.25 on 2025-11-22 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_integration', '0002_alter_smsmessage_patient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smstemplate',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AddField(
            model_name='smstemplate',
            name='category',
            field=models.CharField(choices=[('appointment_reminder', 'Appointment Reminder'), ('appointment_confirmation', 'Appointment Confirmation'), ('followup_reminder', 'Follow-up Reminder'), ('cancellation', 'Cancellation Notice'), ('rescheduling', 'Rescheduling'), ('general', 'General Communication'), ('special', 'Birthday/Special')], default='general', help_text='Template category for organization', max_length=50),
        ),
        migrations.AddField(
            model_name='smstemplate',
            name='character_count',
            field=models.IntegerField(default=0, help_text='Approximate character count (calculated on save)'),
        ),
        migrations.AddField(
            model_name='smstemplate',
            name='created_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='smstemplate',
            name='sms_segment_count',
            field=models.IntegerField(default=1, help_text='Estimated SMS segments (160 chars = 1, then 153 per segment)'),
        ),
        migrations.AlterField(
            model_name='smstemplate',
            name='message_template',
            field=models.TextField(help_text='Template text. Variables: {patient_name}, {appointment_date}, {appointment_time}, {clinic_name}, {clinician_name}, etc.'),
        ),
    ]
