# Generated by Django 4.2.25 on 2025-11-08 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_integration', '0003_smsinbound_download_status_smsinbound_has_media_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsmessage',
            name='has_media',
            field=models.BooleanField(default=False, help_text='Does this message include media (image)?'),
        ),
        migrations.AddField(
            model_name='smsmessage',
            name='media_filename',
            field=models.CharField(blank=True, help_text='Original filename', max_length=255),
        ),
        migrations.AddField(
            model_name='smsmessage',
            name='media_size',
            field=models.IntegerField(blank=True, help_text='Media file size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='smsmessage',
            name='media_type',
            field=models.CharField(blank=True, help_text='MIME type (e.g., image/jpeg, image/png)', max_length=50),
        ),
        migrations.AddField(
            model_name='smsmessage',
            name='media_url',
            field=models.URLField(blank=True, help_text='Public S3 URL for media file (for sending to SMS provider)', max_length=1024),
        ),
        migrations.AddField(
            model_name='smsmessage',
            name='s3_key',
            field=models.CharField(blank=True, help_text='S3 object key (path in bucket: mms/outbound/)', max_length=500),
        ),
    ]
