# Generated by Django 4.2.25 on 2025-11-22 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinicians', '0006_change_professional_url_to_charfield'),
        ('sms_integration', '0003_add_template_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smstemplate',
            options={'ordering': ['clinic', 'category', 'name']},
        ),
        migrations.AddField(
            model_name='smstemplate',
            name='clinic',
            field=models.ForeignKey(blank=True, help_text='Specific clinic this template belongs to (blank = available to all clinics)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_templates', to='clinicians.clinic'),
        ),
    ]
