# Generated by Django 4.2.25 on 2025-11-04 19:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinicians', '0001_initial'),
        ('patients', '0004_patient_patients_archive_5c56ec_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique reminder identifier (UUID)', primary_key=True, serialize=False)),
                ('note', models.TextField(help_text='Reminder note/description')),
                ('reminder_date', models.DateField(blank=True, help_text='Specific date for this reminder (optional)', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Reminder status', max_length=20)),
                ('appointment_id', models.UUIDField(blank=True, help_text='Link to appointment if reminder was converted', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when reminder was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when reminder was last updated')),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='Timestamp when reminder was converted to appointment', null=True)),
                ('created_by', models.CharField(blank=True, help_text='User who created this reminder (optional)', max_length=100, null=True)),
                ('clinic', models.ForeignKey(blank=True, help_text='Clinic location for this reminder', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='clinicians.clinic')),
                ('patient', models.ForeignKey(help_text='Patient this reminder is for', on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Reminder',
                'verbose_name_plural': 'Reminders',
                'db_table': 'reminders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='reminders_status_9617ae_idx'), models.Index(fields=['clinic', 'status'], name='reminders_clinic__ef25d1_idx'), models.Index(fields=['patient'], name='reminders_patient_f08f32_idx'), models.Index(fields=['reminder_date'], name='reminders_reminde_eebc36_idx')],
            },
        ),
    ]
