# Generated by Django 4.2.25 on 2025-11-07 02:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0005_patient_plan_dates_json_alter_patient_plan_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientLetter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique letter identifier (UUID)', primary_key=True, serialize=False)),
                ('letter_type', models.CharField(help_text='Type of letter (e.g., Support Letter, Follow-up Letter, etc.)', max_length=255)),
                ('recipient_name', models.CharField(blank=True, help_text="Recipient's name (optional)", max_length=255)),
                ('subject', models.CharField(blank=True, help_text='Letter subject/title (optional)', max_length=255)),
                ('pages', models.JSONField(default=list, help_text="Array of HTML content for each page: ['<p>Page 1...</p>', '<p>Page 2...</p>']")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the letter was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the letter was last modified')),
                ('patient', models.ForeignKey(help_text='Patient this letter is for', on_delete=django.db.models.deletion.CASCADE, related_name='letters', to='patients.patient')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['patient', '-updated_at'], name='letters_pat_patient_e90a89_idx'), models.Index(fields=['letter_type'], name='letters_pat_letter__a1a31d_idx')],
            },
        ),
    ]
