# Generated by Django 4.2.25 on 2025-11-04 22:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0005_patient_plan_dates_json_alter_patient_plan_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique note identifier (UUID)', primary_key=True, serialize=False)),
                ('note_type', models.CharField(choices=[('clinical_notes', 'Clinical Notes'), ('clinic_dates', 'Clinic Dates'), ('order_notes', 'Order Notes'), ('admin_notes', 'Admin Notes'), ('referral', 'Referral'), ('3d_scan_data', '3D Scan Data'), ('workshop_note', 'Workshop Note'), ('other', 'Other')], default='clinical_notes', help_text='Type of note', max_length=50)),
                ('content', models.TextField(help_text='Note content')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when note was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when note was last updated')),
                ('created_by', models.CharField(blank=True, help_text='User who created this note (optional)', max_length=100, null=True)),
                ('patient', models.ForeignKey(help_text='Patient this note belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='patient_notes', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'db_table': 'notes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient'], name='notes_patient_451fda_idx'), models.Index(fields=['note_type'], name='notes_note_ty_1156b6_idx'), models.Index(fields=['patient', 'note_type'], name='notes_patient_9b3868_idx'), models.Index(fields=['-created_at'], name='notes_created_f9cdd1_idx')],
            },
        ),
    ]
